# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='review',
            field=models.TextField(help_text='Enter a review'),
        ),
    ]
