# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20171202_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='url',
        ),
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.CharField(help_text='Eneter the game website', max_length=1000, null=True),
        ),
    ]
