# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171202_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.CharField(help_text='Put the link for the game box image', max_length=1000, null=True),
        ),
    ]
