# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
