# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_game_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(blank=True, help_text='Enter the date the game is released', null=True),
        ),
    ]
