# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_game_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='month',
            field=models.ManyToManyField(help_text='Select the month the game was released', to='catalog.Month'),
        ),
    ]
